### ISSUE TITLE
pretrain_OAG.py hgt

### ISSUE THREAD

**Issue by TOMeoww** [acbull/GPT-GNN#6]
Thanks for your great work. I try to run the pretrain_OAG.py and get this error.
Traceback (most recent call last):
  File "/home/tiaoban/chen_qian_yu/gptgnn/GPT-GNN/example_OAG/pretrain_OAG.py", line 228, in <module>
    node_emb = gpt_gnn.gnn(node_feature.to(device), node_type.to(device), edge_time.to(device), edge_index.to(device), edge_type.to(device))
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tiaoban/chen_qian_yu/gptgnn/GPT-GNN/example_OAG/GPT_GNN/model.py", line 191, in forward
    meta_xs = gc(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tiaoban/chen_qian_yu/gptgnn/GPT-GNN/example_OAG/GPT_GNN/conv.py", line 169, in forward
    return self.base_conv(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tiaoban/chen_qian_yu/gptgnn/GPT-GNN/example_OAG/GPT_GNN/conv.py", line 55, in forward
    edge_type=edge_type, edge_time = edge_time)
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 233, in propagate
    kwargs)
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 156, in __collect__
    self.__set_size__(size, dim, data)
  File "/home/tiaoban/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 118, in __set_size__
    size[dim] = src.size(self.node_dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

There are any problems with the pretrain_OAG.py?Thanks!

**Comment by acbull** [comment]
Which pyG version are you using? We are using:

pytorch_geometric 1.3.2
torch-cluster==1.4.5
torch-scatter==1.3.2
torch-sparse==0.4.3

**Comment by TOMeoww** [comment]
torch-geometric 1.6.0
torch-scatter==2.0.5
torch-sparse==0.6.6
torch-cluster==1.5.6

**Comment by acbull** [comment]
I think it's the problem of pyG version. There're also some other people get the same error due to the version difference. I'll later check how to adapt to the newer version. Right now can you try using the older version that I sent to you?

**Comment by TOMeoww** [comment]
Yes！Thanks for your hardworking！
